### ISSUE TITLE
连不上，错误代码1

### ISSUE THREAD

**Issue by KAWOSEN** [wcmbeta/GFWdata#3]
win10 系统，试了很多，都是一样的错误

**Comment by wcmbeta** [comment]
具体什么工具

**Comment by KAWOSEN** [comment]
我以为在那个下载页面，可以对应到那个工具。我用的是

SoftEther VPN（推荐）

我下载安装了，有那么1个或2个偶尔显示连接上了，但是用不了几秒又错误断开

**Comment by wcmbeta** [comment]
尝试使用新版本，刷新列表，win7下测试良好
