### ISSUE TITLE
shadowsocks-android本地开发调试

### ISSUE THREAD

**Issue by ncc0706** [wcmbeta/GFWdata#4]
您好，shadowsocks-android这个项目怎么本地开发调试？

**Comment by wcmbeta** [comment]
照着项目文档做就可以

**Comment by ncc0706** [comment]
@wcmbeta 文档只有的编译打包，我想边调试边看页面的开发

**Comment by wcmbeta** [comment]
AndroidStudio debug模式能胜任你的需求吗

**Comment by ncc0706** [comment]
可以的，就是不知道怎么用AndroidStudio运行

**Comment by ncc0706** [comment]
我就想自己编译一个可以自动爬取ss账号的apk
